Controllers/FriendController.cs
using Medhavi_MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
namespace Medhavi_MVC.Controllers
{
    public class FriendController : Controller
    {
        private readonly ApplicationDbContext _db;
        public FriendController(ApplicationDbContext db)
        {
            _db = db;
        }


        // GET: FriendController
        public ActionResult Index()
        {
            IEnumerable<Friend> friends = _db.Friend.ToList();
            return View(friends);
        }

        // GET: FriendController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FriendController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FriendController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Friend friend)
        {
            if (ModelState.IsValid)
            {
                _db.Friend.Add(friend);
                _db.SaveChanges();
                TempData["Sucess"] = "Friend  Added sucessfully";
                return RedirectToAction("Index");
            }
            return View(friend);
        }

        

        // GET: FriendController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FriendController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FriendController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FriendController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;

namespace Medhavi_MVC.Controllers
{
    public class StudentController : Controller
    {
        // GET: StudentController
        public ActionResult Index()
        {
            return View();
        }

        // GET: StudentController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: StudentController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StudentController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StudentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StudentController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StudentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/TeacherController.cs
using Medhavi_MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Medhavi_MVC.Controllers
{
    [Authorize]
    public class TeacherController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        public TeacherController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }
        public IActionResult Index()
        {
            var list = _applicationDbContext.Teachers.ToList();
            return View(list);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _applicationDbContext.Add(teacher);
                _applicationDbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(teacher);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var cover = _applicationDbContext.Teachers.Find(id);
            if (cover == null)
            {
                return NotFound();
            }
            return View(cover);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _applicationDbContext.Update(teacher);
                _applicationDbContext.SaveChanges();
                TempData["Sucess"] = "Teacher Edited sucessfully";
                return RedirectToAction("Index");
            }
            return View(teacher);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var cover = _applicationDbContext.Teachers.Where(x => x.Id == id).FirstOrDefault();
            return View(cover);


        }
        //post
        [HttpPost]
        public IActionResult Delete(Teacher teacher)
        {
            _applicationDbContext.Teachers.Remove(teacher);
            _applicationDbContext.SaveChanges();
            TempData["Sucess"] = "Teacher deleted sucessfully";
            return RedirectToAction("Index");

        }

    }
}

Controllers/UserAccountController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Win32;
using System.Security.Claims;
using System.Text;
using Medhavi_MVC.Models;
using Medhavi_MVC.ViewModels;
using System.Security.Cryptography;

namespace Medhavi_MVC.Controllers
{
    public class UserAccountController : Controller
    {
        readonly ApplicationDbContext _applicationDbContext;
        public UserAccountController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Login(UserAccountViewModel userAccountViewModel)
        {
            if (ModelState.IsValid)
            {
                UserAccount? userAccount = _applicationDbContext.UserAccount.Where(x => x.UserName == userAccountViewModel.UserName).FirstOrDefault();
                if (userAccount == null)
                {
                    return BadRequest("User Not Found");
                }
                var hashedPassword = HashPassword(userAccountViewModel.PassWord);
                if (userAccount.PassWord != hashedPassword)
                {
                    return View(userAccount);
                }
                else
                {

                    var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, userAccount.UserName),
                    new Claim(ClaimTypes.Role, userAccount.RoleName),
                };
                    var claimsIdentity = new ClaimsIdentity(
                        claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties = new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.Now.AddMinutes(10),
                    };
                    await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties);
                    return RedirectToAction("Index", "Home");
                }

            }
            return View(userAccountViewModel);
        }

        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(UserAccount userAccount)
        {
            if (ModelState.IsValid)
            {
                userAccount.PassWord = HashPassword(userAccount.PassWord);
                _applicationDbContext.UserAccount.Add(userAccount);
                _applicationDbContext.SaveChanges();
                return RedirectToAction("Login");
            }
            return View(userAccount);
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
        private string HashPassword(string password)
        {
            using (var sha256 = SHA256.Create())
            {
                byte[] hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
                return Convert.ToBase64String(hashedBytes);
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Medhavi_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Medhavi_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Medhavi_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Teacher" asp-action="Index">Teacher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="UserAccount" asp-action="Register">User Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Friend" asp-action="Index">Friend</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Medhavi_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>